<?php

use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{
  public function run()
  {
  	DB::statement('SET FOREIGN_KEY_CHECKS = 0');
  	DB::table('countries')->truncate();
    DB::statement('SET FOREIGN_KEY_CHECKS = 1');
    
    $countries = [
    	['iso' => 'AF', 'name' => 'Afghanistan', 'phonecode' => 93],
		['iso' => 'AL', 'name' => 'Albania', 'phonecode' => 355],
		['iso' => 'DZ', 'name' => 'Algeria', 'phonecode' => 213],
		['iso' => 'AS', 'name' => 'American Samoa', 'phonecode' => 1684],
		['iso' => 'AD', 'name' => 'Andorra', 'phonecode' => 376],
		['iso' => 'AO', 'name' => 'Angola', 'phonecode' => 244],
		['iso' => 'AI', 'name' => 'Anguilla', 'phonecode' => 1264],
		['iso' => 'AQ', 'name' => 'Antarctica', 'phonecode' => 0],
		['iso' => 'AG', 'name' => 'Antigua And Barbuda', 'phonecode' => 1268],
		['iso' => 'AR', 'name' => 'Argentina', 'phonecode' => 54],
		['iso' => 'AM', 'name' => 'Armenia', 'phonecode' => 374],
		['iso' => 'AW', 'name' => 'Aruba', 'phonecode' => 297],
		['iso' => 'AU', 'name' => 'Australia', 'phonecode' => 61],
		['iso' => 'AT', 'name' => 'Austria', 'phonecode' => 43],
		['iso' => 'AZ', 'name' => 'Azerbaijan', 'phonecode' => 994],
		['iso' => 'BS', 'name' => 'Bahamas The', 'phonecode' => 1242],
		['iso' => 'BH', 'name' => 'Bahrain', 'phonecode' => 973],
		['iso' => 'BD', 'name' => 'Bangladesh', 'phonecode' => 880],
		['iso' => 'BB', 'name' => 'Barbados', 'phonecode' => 1246],
		['iso' => 'BY', 'name' => 'Belarus', 'phonecode' => 375],
		['iso' => 'BE', 'name' => 'Belgium', 'phonecode' => 32],
		['iso' => 'BZ', 'name' => 'Belize', 'phonecode' => 501],
		['iso' => 'BJ', 'name' => 'Benin', 'phonecode' => 229],
		['iso' => 'BM', 'name' => 'Bermuda', 'phonecode' => 1441],
		['iso' => 'BT', 'name' => 'Bhutan', 'phonecode' => 975],
		['iso' => 'BO', 'name' => 'Bolivia', 'phonecode' => 591],
		['iso' => 'BA', 'name' => 'Bosnia and Herzegovina', 'phonecode' => 387],
		['iso' => 'BW', 'name' => 'Botswana', 'phonecode' => 267],
		['iso' => 'BV', 'name' => 'Bouvet Island', 'phonecode' => 0],
		['iso' => 'BR', 'name' => 'Brazil', 'phonecode' => 55],
		['iso' => 'IO', 'name' => 'British Indian Ocean Territory', 'phonecode' => 246],
		['iso' => 'BN', 'name' => 'Brunei', 'phonecode' => 673],
		['iso' => 'BG', 'name' => 'Bulgaria', 'phonecode' => 359],
		['iso' => 'BF', 'name' => 'Burkina Faso', 'phonecode' => 226],
		['iso' => 'BI', 'name' => 'Burundi', 'phonecode' => 257],
		['iso' => 'KH', 'name' => 'Cambodia', 'phonecode' => 855],
		['iso' => 'CM', 'name' => 'Cameroon', 'phonecode' => 237],
		['iso' => 'CA', 'name' => 'Canada', 'phonecode' => 1],
		['iso' => 'CV', 'name' => 'Cape Verde', 'phonecode' => 238],
		['iso' => 'KY', 'name' => 'Cayman Islands', 'phonecode' => 1345],
		['iso' => 'CF', 'name' => 'Central African Republic', 'phonecode' => 236],
		['iso' => 'TD', 'name' => 'Chad', 'phonecode' => 235],
		['iso' => 'CL', 'name' => 'Chile', 'phonecode' => 56],
		['iso' => 'CN', 'name' => 'China', 'phonecode' => 86],
		['iso' => 'CX', 'name' => 'Christmas Island', 'phonecode' => 61],
		['iso' => 'CC', 'name' => 'Cocos (Keeling) Islands', 'phonecode' => 672],
		['iso' => 'CO', 'name' => 'Colombia', 'phonecode' => 57],
		['iso' => 'KM', 'name' => 'Comoros', 'phonecode' => 269],
		['iso' => 'CG', 'name' => 'Republic Of The Congo', 'phonecode' => 242],
		['iso' => 'CD', 'name' => 'Democratic Republic Of The Congo', 'phonecode' => 242],
		['iso' => 'CK', 'name' => 'Cook Islands', 'phonecode' => 682],
		['iso' => 'CR', 'name' => 'Costa Rica', 'phonecode' => 506],
		['iso' => 'CI', 'name' => 'Cote D\'Ivoire (Ivory Coast)', 'phonecode' => 225],
		['iso' => 'HR', 'name' => 'Croatia (Hrvatska)', 'phonecode' => 385],
		['iso' => 'CU', 'name' => 'Cuba', 'phonecode' => 53],
		['iso' => 'CY', 'name' => 'Cyprus', 'phonecode' => 357],
		['iso' => 'CZ', 'name' => 'Czech Republic', 'phonecode' => 420],
		['iso' => 'DK', 'name' => 'Denmark', 'phonecode' => 45],
		['iso' => 'DJ', 'name' => 'Djibouti', 'phonecode' => 253],
		['iso' => 'DM', 'name' => 'Dominica', 'phonecode' => 1767],
		['iso' => 'DO', 'name' => 'Dominican Republic', 'phonecode' => 1809],
		['iso' => 'TP', 'name' => 'East Timor', 'phonecode' => 670],
		['iso' => 'EC', 'name' => 'Ecuador', 'phonecode' => 593],
		['iso' => 'EG', 'name' => 'Egypt', 'phonecode' => 20],
		['iso' => 'SV', 'name' => 'El Salvador', 'phonecode' => 503],
		['iso' => 'GQ', 'name' => 'Equatorial Guinea', 'phonecode' => 240],
		['iso' => 'ER', 'name' => 'Eritrea', 'phonecode' => 291],
		['iso' => 'EE', 'name' => 'Estonia', 'phonecode' => 372],
		['iso' => 'ET', 'name' => 'Ethiopia', 'phonecode' => 251],
		['iso' => 'XA', 'name' => 'External Territories of Australia', 'phonecode' => 61],
		['iso' => 'FK', 'name' => 'Falkland Islands', 'phonecode' => 500],
		['iso' => 'FO', 'name' => 'Faroe Islands', 'phonecode' => 298],
		['iso' => 'FJ', 'name' => 'Fiji Islands', 'phonecode' => 679],
		['iso' => 'FI', 'name' => 'Finland', 'phonecode' => 358],
		['iso' => 'FR', 'name' => 'France', 'phonecode' => 33],
		['iso' => 'GF', 'name' => 'French Guiana', 'phonecode' => 594],
		['iso' => 'PF', 'name' => 'French Polynesia', 'phonecode' => 689],
		['iso' => 'TF', 'name' => 'French Southern Territories', 'phonecode' => 0],
		['iso' => 'GA', 'name' => 'Gabon', 'phonecode' => 241],
		['iso' => 'GM', 'name' => 'Gambia The', 'phonecode' => 220],
		['iso' => 'GE', 'name' => 'Georgia', 'phonecode' => 995],
		['iso' => 'DE', 'name' => 'Germany', 'phonecode' => 49],
		['iso' => 'GH', 'name' => 'Ghana', 'phonecode' => 233],
		['iso' => 'GI', 'name' => 'Gibraltar', 'phonecode' => 350],
		['iso' => 'GR', 'name' => 'Greece', 'phonecode' => 30],
		['iso' => 'GL', 'name' => 'Greenland', 'phonecode' => 299],
		['iso' => 'GD', 'name' => 'Grenada', 'phonecode' => 1473],
		['iso' => 'GP', 'name' => 'Guadeloupe', 'phonecode' => 590],
		['iso' => 'GU', 'name' => 'Guam', 'phonecode' => 1671],
		['iso' => 'GT', 'name' => 'Guatemala', 'phonecode' => 502],
		['iso' => 'XU', 'name' => 'Guernsey and Alderney', 'phonecode' => 44],
		['iso' => 'GN', 'name' => 'Guinea', 'phonecode' => 224],
		['iso' => 'GW', 'name' => 'Guinea-Bissau', 'phonecode' => 245],
		['iso' => 'GY', 'name' => 'Guyana', 'phonecode' => 592],
		['iso' => 'HT', 'name' => 'Haiti', 'phonecode' => 509],
		['iso' => 'HM', 'name' => 'Heard and McDonald Islands', 'phonecode' => 0],
		['iso' => 'HN', 'name' => 'Honduras', 'phonecode' => 504],
		['iso' => 'HK', 'name' => 'Hong Kong S.A.R.', 'phonecode' => 852],
		['iso' => 'HU', 'name' => 'Hungary', 'phonecode' => 36],
		['iso' => 'IS', 'name' => 'Iceland', 'phonecode' => 354],
		['iso' => 'IN', 'name' => 'India', 'phonecode' => 91],
		['iso' => 'ID', 'name' => 'Indonesia', 'phonecode' => 62],
		['iso' => 'IR', 'name' => 'Iran', 'phonecode' => 98],
		['iso' => 'IQ', 'name' => 'Iraq', 'phonecode' => 964],
		['iso' => 'IE', 'name' => 'Ireland', 'phonecode' => 353],
		['iso' => 'IL', 'name' => 'Israel', 'phonecode' => 972],
		['iso' => 'IT', 'name' => 'Italy', 'phonecode' => 39],
		['iso' => 'JM', 'name' => 'Jamaica', 'phonecode' => 1876],
		['iso' => 'JP', 'name' => 'Japan', 'phonecode' => 81],
		['iso' => 'XJ', 'name' => 'Jersey', 'phonecode' => 44],
		['iso' => 'JO', 'name' => 'Jordan', 'phonecode' => 962],
		['iso' => 'KZ', 'name' => 'Kazakhstan', 'phonecode' => 7],
		['iso' => 'KE', 'name' => 'Kenya', 'phonecode' => 254],
		['iso' => 'KI', 'name' => 'Kiribati', 'phonecode' => 686],
		['iso' => 'KP', 'name' => 'Korea North', 'phonecode' => 850],
		['iso' => 'KR', 'name' => 'Korea South', 'phonecode' => 82],
		['iso' => 'KW', 'name' => 'Kuwait', 'phonecode' => 965],
		['iso' => 'KG', 'name' => 'Kyrgyzstan', 'phonecode' => 996],
		['iso' => 'LA', 'name' => 'Laos', 'phonecode' => 856],
		['iso' => 'LV', 'name' => 'Latvia', 'phonecode' => 371],
		['iso' => 'LB', 'name' => 'Lebanon', 'phonecode' => 961],
		['iso' => 'LS', 'name' => 'Lesotho', 'phonecode' => 266],
		['iso' => 'LR', 'name' => 'Liberia', 'phonecode' => 231],
		['iso' => 'LY', 'name' => 'Libya', 'phonecode' => 218],
		['iso' => 'LI', 'name' => 'Liechtenstein', 'phonecode' => 423],
		['iso' => 'LT', 'name' => 'Lithuania', 'phonecode' => 370],
		['iso' => 'LU', 'name' => 'Luxembourg', 'phonecode' => 352],
		['iso' => 'MO', 'name' => 'Macau S.A.R.', 'phonecode' => 853],
		['iso' => 'MK', 'name' => 'Macedonia', 'phonecode' => 389],
		['iso' => 'MG', 'name' => 'Madagascar', 'phonecode' => 261],
		['iso' => 'MW', 'name' => 'Malawi', 'phonecode' => 265],
		['iso' => 'MY', 'name' => 'Malaysia', 'phonecode' => 60],
		['iso' => 'MV', 'name' => 'Maldives', 'phonecode' => 960],
		['iso' => 'ML', 'name' => 'Mali', 'phonecode' => 223],
		['iso' => 'MT', 'name' => 'Malta', 'phonecode' => 356],
		['iso' => 'XM', 'name' => 'Man (Isle of)', 'phonecode' => 44],
		['iso' => 'MH', 'name' => 'Marshall Islands', 'phonecode' => 692],
		['iso' => 'MQ', 'name' => 'Martinique', 'phonecode' => 596],
		['iso' => 'MR', 'name' => 'Mauritania', 'phonecode' => 222],
		['iso' => 'MU', 'name' => 'Mauritius', 'phonecode' => 230],
		['iso' => 'YT', 'name' => 'Mayotte', 'phonecode' => 269],
		['iso' => 'MX', 'name' => 'Mexico', 'phonecode' => 52],
		['iso' => 'FM', 'name' => 'Micronesia', 'phonecode' => 691],
		['iso' => 'MD', 'name' => 'Moldova', 'phonecode' => 373],
		['iso' => 'MC', 'name' => 'Monaco', 'phonecode' => 377],
		['iso' => 'MN', 'name' => 'Mongolia', 'phonecode' => 976],
		['iso' => 'MS', 'name' => 'Montserrat', 'phonecode' => 1664],
		['iso' => 'MA', 'name' => 'Morocco', 'phonecode' => 212],
		['iso' => 'MZ', 'name' => 'Mozambique', 'phonecode' => 258],
		['iso' => 'MM', 'name' => 'Myanmar', 'phonecode' => 95],
		['iso' => 'NA', 'name' => 'Namibia', 'phonecode' => 264],
		['iso' => 'NR', 'name' => 'Nauru', 'phonecode' => 674],
		['iso' => 'NP', 'name' => 'Nepal', 'phonecode' => 977],
		['iso' => 'AN', 'name' => 'Netherlands Antilles', 'phonecode' => 599],
		['iso' => 'NL', 'name' => 'Netherlands The', 'phonecode' => 31],
		['iso' => 'NC', 'name' => 'New Caledonia', 'phonecode' => 687],
		['iso' => 'NZ', 'name' => 'New Zealand', 'phonecode' => 64],
		['iso' => 'NI', 'name' => 'Nicaragua', 'phonecode' => 505],
		['iso' => 'NE', 'name' => 'Niger', 'phonecode' => 227],
		['iso' => 'NG', 'name' => 'Nigeria', 'phonecode' => 234],
		['iso' => 'NU', 'name' => 'Niue', 'phonecode' => 683],
		['iso' => 'NF', 'name' => 'Norfolk Island', 'phonecode' => 672],
		['iso' => 'MP', 'name' => 'Northern Mariana Islands', 'phonecode' => 1670],
		['iso' => 'NO', 'name' => 'Norway', 'phonecode' => 47],
		['iso' => 'OM', 'name' => 'Oman', 'phonecode' => 968],
		['iso' => 'PK', 'name' => 'Pakistan', 'phonecode' => 92],
		['iso' => 'PW', 'name' => 'Palau', 'phonecode' => 680],
		['iso' => 'PS', 'name' => 'Palestinian Territory Occupied', 'phonecode' => 970],
		['iso' => 'PA', 'name' => 'Panama', 'phonecode' => 507],
		['iso' => 'PG', 'name' => 'Papua new Guinea', 'phonecode' => 675],
		['iso' => 'PY', 'name' => 'Paraguay', 'phonecode' => 595],
		['iso' => 'PE', 'name' => 'Peru', 'phonecode' => 51],
		['iso' => 'PH', 'name' => 'Philippines', 'phonecode' => 63],
		['iso' => 'PN', 'name' => 'Pitcairn Island', 'phonecode' => 0],
		['iso' => 'PL', 'name' => 'Poland', 'phonecode' => 48],
		['iso' => 'PT', 'name' => 'Portugal', 'phonecode' => 351],
		['iso' => 'PR', 'name' => 'Puerto Rico', 'phonecode' => 1787],
		['iso' => 'QA', 'name' => 'Qatar', 'phonecode' => 974],
		['iso' => 'RE', 'name' => 'Reunion', 'phonecode' => 262],
		['iso' => 'RO', 'name' => 'Romania', 'phonecode' => 40],
		['iso' => 'RU', 'name' => 'Russia', 'phonecode' => 70],
		['iso' => 'RW', 'name' => 'Rwanda', 'phonecode' => 250],
		['iso' => 'SH', 'name' => 'Saint Helena', 'phonecode' => 290],
		['iso' => 'KN', 'name' => 'Saint Kitts And Nevis', 'phonecode' => 1869],
		['iso' => 'LC', 'name' => 'Saint Lucia', 'phonecode' => 1758],
		['iso' => 'PM', 'name' => 'Saint Pierre and Miquelon', 'phonecode' => 508],
		['iso' => 'VC', 'name' => 'Saint Vincent And The Grenadines', 'phonecode' => 1784],
		['iso' => 'WS', 'name' => 'Samoa', 'phonecode' => 684],
		['iso' => 'SM', 'name' => 'San Marino', 'phonecode' => 378],
		['iso' => 'ST', 'name' => 'Sao Tome and Principe', 'phonecode' => 239],
		['iso' => 'SA', 'name' => 'Saudi Arabia', 'phonecode' => 966],
		['iso' => 'SN', 'name' => 'Senegal', 'phonecode' => 221],
		['iso' => 'RS', 'name' => 'Serbia', 'phonecode' => 381],
		['iso' => 'SC', 'name' => 'Seychelles', 'phonecode' => 248],
		['iso' => 'SL', 'name' => 'Sierra Leone', 'phonecode' => 232],
		['iso' => 'SG', 'name' => 'Singapore', 'phonecode' => 65],
		['iso' => 'SK', 'name' => 'Slovakia', 'phonecode' => 421],
		['iso' => 'SI', 'name' => 'Slovenia', 'phonecode' => 386],
		['iso' => 'XG', 'name' => 'Smaller Territories of the UK', 'phonecode' => 44],
		['iso' => 'SB', 'name' => 'Solomon Islands', 'phonecode' => 677],
		['iso' => 'SO', 'name' => 'Somalia', 'phonecode' => 252],
		['iso' => 'ZA', 'name' => 'South Africa', 'phonecode' => 27],
		['iso' => 'GS', 'name' => 'South Georgia', 'phonecode' => 0],
		['iso' => 'SS', 'name' => 'South Sudan', 'phonecode' => 211],
		['iso' => 'ES', 'name' => 'Spain', 'phonecode' => 34],
		['iso' => 'LK', 'name' => 'Sri Lanka', 'phonecode' => 94],
		['iso' => 'SD', 'name' => 'Sudan', 'phonecode' => 249],
		['iso' => 'SR', 'name' => 'Suriname', 'phonecode' => 597],
		['iso' => 'SJ', 'name' => 'Svalbard And Jan Mayen Islands', 'phonecode' => 47],
		['iso' => 'SZ', 'name' => 'Swaziland', 'phonecode' => 268],
		['iso' => 'SE', 'name' => 'Sweden', 'phonecode' => 46],
		['iso' => 'CH', 'name' => 'Switzerland', 'phonecode' => 41],
		['iso' => 'SY', 'name' => 'Syria', 'phonecode' => 963],
		['iso' => 'TW', 'name' => 'Taiwan', 'phonecode' => 886],
		['iso' => 'TJ', 'name' => 'Tajikistan', 'phonecode' => 992],
		['iso' => 'TZ', 'name' => 'Tanzania', 'phonecode' => 255],
		['iso' => 'TH', 'name' => 'Thailand', 'phonecode' => 66],
		['iso' => 'TG', 'name' => 'Togo', 'phonecode' => 228],
		['iso' => 'TK', 'name' => 'Tokelau', 'phonecode' => 690],
		['iso' => 'TO', 'name' => 'Tonga', 'phonecode' => 676],
		['iso' => 'TT', 'name' => 'Trinidad And Tobago', 'phonecode' => 1868],
		['iso' => 'TN', 'name' => 'Tunisia', 'phonecode' => 216],
		['iso' => 'TR', 'name' => 'Turkey', 'phonecode' => 90],
		['iso' => 'TM', 'name' => 'Turkmenistan', 'phonecode' => 7370],
		['iso' => 'TC', 'name' => 'Turks And Caicos Islands', 'phonecode' => 1649],
		['iso' => 'TV', 'name' => 'Tuvalu', 'phonecode' => 688],
		['iso' => 'UG', 'name' => 'Uganda', 'phonecode' => 256],
		['iso' => 'UA', 'name' => 'Ukraine', 'phonecode' => 380],
		['iso' => 'AE', 'name' => 'United Arab Emirates', 'phonecode' => 971],
		['iso' => 'GB', 'name' => 'United Kingdom', 'phonecode' => 44],
		['iso' => 'US', 'name' => 'United States', 'phonecode' => 1],
		['iso' => 'UM', 'name' => 'United States Minor Outlying Islands', 'phonecode' => 1],
		['iso' => 'UY', 'name' => 'Uruguay', 'phonecode' => 598],
		['iso' => 'UZ', 'name' => 'Uzbekistan', 'phonecode' => 998],
		['iso' => 'VU', 'name' => 'Vanuatu', 'phonecode' => 678],
		['iso' => 'VA', 'name' => 'Vatican City State (Holy See)', 'phonecode' => 39],
		['iso' => 'VE', 'name' => 'Venezuela', 'phonecode' => 58],
		['iso' => 'VN', 'name' => 'Vietnam', 'phonecode' => 84],
		['iso' => 'VG', 'name' => 'Virgin Islands (British)', 'phonecode' => 1284],
		['iso' => 'VI', 'name' => 'Virgin Islands (US)', 'phonecode' => 1340],
		['iso' => 'WF', 'name' => 'Wallis And Futuna Islands', 'phonecode' => 681],
		['iso' => 'EH', 'name' => 'Western Sahara', 'phonecode' => 212],
		['iso' => 'YE', 'name' => 'Yemen', 'phonecode' => 967],
		['iso' => 'YU', 'name' => 'Yugoslavia', 'phonecode' => 38],
		['iso' => 'ZM', 'name' => 'Zambia', 'phonecode' => 260],
		['iso' => 'ZW', 'name' => 'Zimbabwe', 'phonecode' => 263],
    ];

    DB::table('countries')->insert($countries);
  }
}
